[project]
authors = [{ name = "Rhys Davies", email = "rhys@memes.nz" }]
requires-python = "<4.0,>=3.11"
dependencies = [
    "pulumi==3.218.0",
    "pulumi-gcp==9.10.0",
    "pulumi-google-native==0.32.0",
    "pulumi-azure-native==2.73.0",
    "pulumi-docker==4.11.0",
    "pulumi-aws==7.16.0",
    "pulumi-containerregistry==0.0.14",
    "pulumi-alicloud==3.93.0",
    "setuptools==80.10.2",
    "pulumi-std==2.2.0",
    "pip==26.0",
    "pulumi-docker-build==0.0.15",
]
name = "pingall"
version = "0.1.0"
description = ""
readme = "README.md"
package-mode = false
